cache:
- c:\protobuf-3.6.0-msvc

platform:
- x64

image:
- Visual Studio 2017

environment:
  matrix:
    - TARGET: mingw
    - TARGET: msvc

install:
- git submodule update --init
- for /f "usebackq tokens=*" %%A in (`git rev-parse --short HEAD`) do set "MENOH_REV=%%A"
- echo %MENOH_REV%

- set SSL_CERT_FILE=C:\msys64\mingw64\ssl\cert.pem
- set SSL_CERT_DIR=C:\msys64\mingw64\ssl\certs
- if [%TARGET%]==[mingw] set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
- if [%TARGET%]==[msvc] set PATH=C:\Miniconda3-x64;C:\Miniconda3-x64\Scripts;C:\Miniconda3-x64\Library\bin;%PATH%

- if [%TARGET%]==[mingw] (
    pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-opencv mingw-w64-x86_64-protobuf mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-pip mingw-w64-x86_64-python3-numpy mingw-w64-x86_64-hdf5 mingw-w64-x86_64-ca-certificates &&
    curl -omingw-w64-x86_64-mkl-dnn-0.14-3-x86_64.pkg.tar.xz -L https://github.com/msakai/mkl-dnn/releases/download/v0.14/mingw-w64-x86_64-mkl-dnn-0.14-3-x86_64.pkg.tar.xz &&
    pacman -U --noconfirm mingw-w64-x86_64-mkl-dnn-0.14-3-x86_64.pkg.tar.xz
  ) else (
    curl -omkl-dnn-0.14-win64.7z -L --insecure https://github.com/msakai/mkl-dnn/releases/download/v0.14/mkl-dnn-0.14-win64.7z &&
    mkdir mkl-dnn-0.14-win64 &&
    7z x -omkl-dnn-0.14-win64 mkl-dnn-0.14-win64.7z &&
    call appveyor\install_protoc_msvc.bat
  )

- if [%TARGET%]==[mingw] (
    pip3 install --user chainer &&
    mkdir -p data &&
    python3 retrieve_data.py &&
    python3 gen_test_data.py
  ) else (
    pip install --user chainer &&
    md data &&
    python retrieve_data.py &&
    python gen_test_data.py
  )

build_script:
- mkdir build
- cd build
- if [%TARGET%]==[msvc] set PATH=%PATH%;c:\protobuf-3.6.0-msvc\bin;c:\protobuf-3.6.0-msvc\include;c:\protobuf-3.6.0-msvc\lib;c:\projects\menoh\mkl-dnn-0.14-win64\bin;c:\projects\menoh\mkl-dnn-0.14-win64\include;c:\projects\menoh\mkl-dnn-0.14-win64\lib
- if [%TARGET%]==[mingw] (
    cmake -G "MSYS Makefiles" -DENABLE_TEST=ON -DCMAKE_INSTALL_PREFIX=/mingw64 .. &&
    make
  ) else (
    cmake -G "Visual Studio 14 Win64" -DENABLE_TEST=OFF -DENABLE_BENCHMARK=OFF -DENABLE_EXAMPLE=OFF -DENABLE_TOOL=OFF -DCMAKE_INSTALL_PREFIX=c:\menoh-%MENOH_REV%-msvc .. &&
    cmake --build . --config Release --target install
  )

test_script:
# to find libmenoh.dll, libgtest.dll and libgtest_main.dll
- if [%TARGET%]==[mingw] set PATH=C:\projects\menoh\build\menoh;C:\projects\menoh\build\test\lib\googletest\googlemock\gtest;C:\msys64\mkl-dnn-86b7129-mingw\bin;%PATH%
- if [%TARGET%]==[mingw] (
    ldd test/menoh_test.exe &&
    ldd /c/projects/menoh/build/menoh/libmenoh.dll &&
    ldd /mingw64/bin/libmkldnn.dll &&
    test\menoh_test
  )
- cd ..

after_test:
- if [%TARGET%]==[msvc] (
    7z a menoh-%MENOH_REV%-msvc.zip c:\menoh-%MENOH_REV%-msvc
  )

artifacts:
- path: '*.zip'
